package io.github.lzr.androidapp;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

import io.github.lzr.androidapp.databinding.ActivityMainBinding;

/**
 * Main entry point of the application.
 *
 * This Activity is declared as the launcher activity in AndroidManifest.xml,
 * so it is the first screen shown when the app starts.
 *
 * NOTE: the lecture slides import `android.support.v7.app.AppCompatActivity`.
 * That support library has been retired by Google and no longer compiles, so
 * this project uses its direct replacement, `androidx.appcompat.app.AppCompatActivity`.
 * Everything else is identical to the slides.
 */
public class MainActivity extends AppCompatActivity {

    /**
     * Generated by ViewBinding from res/layout/activity_main.xml.
     * Kept as a field so other lifecycle methods (onStart, onDestroy, ...) can
     * reach the views without calling findViewById again.
     */
    private ActivityMainBinding binding;

    /**
     * Called automatically when the Activity is created.
     * Sets up the initial View for this Activity.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());
    }
}
